apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-pvc
  namespace: log-output
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
