apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-backend
  name: todo-backend
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-backend
    spec:
      containers:
      - image: vinhng10/todo-backend:0.1
        name: todo-backend
        resources: {}
status: {}
