apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-backend-pvc
  namespace: todo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
