apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todo-backend-service
  name: todo-backend-service
  namespace: todo
spec:
  ports:
    - name: 80-8000
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: todo-backend
  type: ClusterIP
status:
  loadBalancer: {}
